on: 
  push:
    branches:
      - webpage
      - main
  workflow_dispatch:

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install libcurl on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libglpk40 libglpk-dev

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: make work folder with data
        if: runner.os == 'Linux'
        run: sudo mkdir -p /work/Intro_to_bulkRNAseq/

      - name: Get data
        if: runner.os == 'Linux'
        run: | 
          sudo wget -O /work/Intro_to_bulkRNAseq/Data.zip  https://zenodo.org/records/12090853/files/Data.zip?download=1
          sudo unzip /work/Intro_to_bulkRNAseq/Data.zip -d /work/Intro_to_bulkRNAseq/
          sudo rm /work/Intro_to_bulkRNAseq/Data.zip

      - name: Install R
        uses: r-lib/actions/setup-r@v2


      - name: Check renv paths
        run: |
          Rscript -e 'cat("Project Library:", renv::paths$library(), "\n")'
          Rscript -e 'cat("Global Cache:", renv::paths$cache(), "\n")'

      - name: Set custom renv library path
        run: echo "RENV_PATHS_LIBRARY=~/renv/library/4.4.2/" >> $GITHUB_ENV
  
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Pull Notebooks folder content
        if: runner.os == 'Linux'
        run: |
          git clone https://github.com/hds-sandbox/bulk_RNAseq_course.git temp_repo
          cp -r temp_repo/Notebooks/*.Rmd develop
          cp -r temp_repo/Notebooks/img/* develop/img/
          rm -rf temp_repo

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        env:
          RENV_PATHS_LIBRARY=~/renv/library/4.4.2/
        with:
          target: gh-pages